### ISSUE TITLE
Fix button sheet

### ISSUE THREAD

**Issue by xmha97** [Bnyro/RecordYou#69] opened 2023-03-07 09:43 UTC
### Steps to reproduce

Tap on settings button.

### Expected behavior

Without margin

### Actual behavior

![Screenshot_2023-03-07-13-10-22-979_com bnyro recorder](https://user-images.githubusercontent.com/23485114/223384330-ce91ebfe-f734-4407-b66f-d6d02154b5d5.jpg)

### Record You version

4.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-07 10:30
Duplicate of #65

**Closed by Bnyro** 2023-03-07 10:30 UTC
Labels: bug
